spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/postgres
    username: postgres

logging:
  level:
    org.jooq: debug
    org.jooq.Constants: off

outpost:
  enabled: true
  parallelism: 10
  batch-size: 100
